name: Greet Everyone

# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  build:
    # Job name is Greeting
    name: Test
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: yarn install
        uses: Borales/actions-yarn@v2.0.1
        with:
          cmd: install # will run `yarn install` command
      # This step prints an output (time) from the previous step's action.
      - name: yarn test
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test # will run `yarn test` command 
